version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pré build phase - exemplo baixar dendências, certificados, etc"
  build:
    commands:
      - echo "Building"
      - mvn clean compile package
  post_build:
    commands:
      - echo "Pos building"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war